title: Cribb Tutoring
description: STEAM tutoring â€” online & Triangle, NC
theme: jekyll-theme-cayman
plugins:
  - jekyll-seo-tag
#  - jekyll-remote-theme
author: Jeremy Cribb
email: cribb.tutoring@gmail.com
timezone: America/New_York
contact_email: cribb.tutoring@gmail.com
area: Triangle, NC
repository: cribb/tutoring-site
url: http://localhost:4000
baseurl: ""

